create sequence crawlerror_id_seq;
alter sequence crawlerror_id_seq owner to ploogle;
create table if not exists books (
    id integer generated by default as identity constraint books_pk primary key,
    title text not null,
    url text not null constraint books_pk_2 unique,
    author text,
    created_at date default now() not null,
    summary text,
    published_at date not null,
    updated_at date not null,
    packaged_at date not null
);
alter table books owner to ploogle;
create table if not exists chapters (
    id integer generated by default as identity constraint chapters_pk primary key,
    url text constraint chapters_pk_2 unique,
    chapter integer,
    chapter_title text,
    book_id integer constraint chapters_books_id_fk references books,
    chapter_text text not null,
    created_at date default now(),
    textsearchable_index_col tsvector generated always as (
        to_tsvector(
            'english'::regconfig,
            ((chapter_title || ' '::text) || chapter_text)
        )
    ) stored
);
alter table chapters owner to ploogle;
create index if not exists textsearch_idx on chapters using gin (textsearchable_index_col);
create table if not exists blacklist (
    id serial constraint blacklist_pk primary key,
    book_id integer not null constraint blacklist_books_id_fk references books,
    created_at date default now(),
    reason text
);
alter table blacklist owner to ploogle;
create table if not exists settings (
    key varchar(255) not null,
    value varchar(255) not null
);
alter table settings owner to ploogle;
create table if not exists crawl_error (
    id integer generated always as identity,
    work_url integer not null,
    created_at date default now() not null
);
alter table crawl_error owner to ploogle;
alter sequence crawlerror_id_seq owned by crawl_error.id;